"""recreate missing head

Revision ID: 1e8242b85a5a
Revises: b1c30fd8ed5e
Create Date: 2026-02-20 13:54:12.948227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8242b85a5a'
down_revision: Union[str, None] = 'b1c30fd8ed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_conversion_events', sa.Column('event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_meta_conversion_events_event_id'), 'meta_conversion_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_conversion_events_event_id'), table_name='meta_conversion_events')
    op.drop_column('meta_conversion_events', 'event_id')
    # ### end Alembic commands ###
