"""add_lead_name_column

Revision ID: 37603be3bd4e
Revises: 1e8242b85a5a
Create Date: 2026-02-24 11:59:58.151213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37603be3bd4e'
down_revision: Union[str, None] = '1e8242b85a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'name')
    # ### end Alembic commands ###
