"""Intial

Revision ID: 44c89edae524
Revises: 
Create Date: 2026-02-27 10:53:27.399946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c89edae524'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igsid', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=True),
    sa.Column('first_event_id', sa.String(), nullable=True),
    sa.Column('first_event_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_contacts_igsid'), 'contacts', ['igsid'], unique=True)
    op.create_index(op.f('ix_contacts_referral_id'), 'contacts', ['referral_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('sudo_admin', 'admin', 'sales_rep', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_external_event_id'), 'webhook_events', ['external_event_id'], unique=False)
    op.create_index('ix_webhook_source_external', 'webhook_events', ['source', 'external_event_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('lead_status', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('referral_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=True),
    sa.Column('text_cleaned', sa.Text(), nullable=True),
    sa.Column('platform_message_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_contact_id'), 'messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_platform_message_id'), 'messages', ['platform_message_id'], unique=False)
    op.create_index(op.f('ix_messages_processed'), 'messages', ['processed'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_lead_id'), 'invoices', ['lead_id'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_customer_id'), 'invoices', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=True)
    op.create_table('meta_conversion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_time', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('action_source', sa.String(), nullable=True),
    sa.Column('messaging_channel', sa.String(), nullable=True),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('partner_agent', sa.String(), nullable=True),
    sa.Column('full_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_conversion_events_event_id'), 'meta_conversion_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_meta_conversion_events_event_name'), 'meta_conversion_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_meta_conversion_events_lead_id'), 'meta_conversion_events', ['lead_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('capi_sent', sa.Boolean(), nullable=False),
    sa.Column('capi_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_invoice_id'), 'payment_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_events_stripe_event_id'), 'payment_events', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_stripe_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_invoice_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_meta_conversion_events_lead_id'), table_name='meta_conversion_events')
    op.drop_index(op.f('ix_meta_conversion_events_event_name'), table_name='meta_conversion_events')
    op.drop_index(op.f('ix_meta_conversion_events_event_id'), table_name='meta_conversion_events')
    op.drop_table('meta_conversion_events')
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_stripe_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_lead_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_messages_processed'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_contact_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_webhook_source_external', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_contacts_referral_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_igsid'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
