"""auto schema sync

Revision ID: 589ff3db70c7
Revises: 
Create Date: 2026-02-19 15:36:24.573976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589ff3db70c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inbound_messages_id', table_name='inbound_messages')
    op.drop_index('ix_inbound_messages_instagram_user_id', table_name='inbound_messages')
    op.drop_index('ix_inbound_messages_lead_id', table_name='inbound_messages')
    op.drop_index('ix_inbound_messages_platform_message_id', table_name='inbound_messages')
    op.drop_index('ix_inbound_messages_processed', table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index('ix_chat_messages_direction', table_name='chat_messages')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_instagram_user_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_lead_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_platform_message_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_meta_conversion_events_event_name', table_name='meta_conversion_events')
    op.drop_index('idx_meta_conversion_events_lead_id', table_name='meta_conversion_events')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_meta_conversion_events_lead_id', 'meta_conversion_events', ['lead_id'], unique=False)
    op.create_index('idx_meta_conversion_events_event_name', 'meta_conversion_events', ['event_name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instagram_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platform_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='chat_messages_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_platform_message_id', 'chat_messages', ['platform_message_id'], unique=False)
    op.create_index('ix_chat_messages_lead_id', 'chat_messages', ['lead_id'], unique=False)
    op.create_index('ix_chat_messages_instagram_user_id', 'chat_messages', ['instagram_user_id'], unique=False)
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_index('ix_chat_messages_direction', 'chat_messages', ['direction'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instagram_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text_raw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_cleaned', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='inbound_messages_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inbound_messages_pkey')
    )
    op.create_index('ix_inbound_messages_processed', 'inbound_messages', ['processed'], unique=False)
    op.create_index('ix_inbound_messages_platform_message_id', 'inbound_messages', ['platform_message_id'], unique=False)
    op.create_index('ix_inbound_messages_lead_id', 'inbound_messages', ['lead_id'], unique=False)
    op.create_index('ix_inbound_messages_instagram_user_id', 'inbound_messages', ['instagram_user_id'], unique=False)
    op.create_index('ix_inbound_messages_id', 'inbound_messages', ['id'], unique=False)
    # ### end Alembic commands ###
