"""add_users_and_lead_assignment_fields

Revision ID: 65983730a7c2
Revises: 37603be3bd4e
Create Date: 2026-02-24 13:06:13.305445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65983730a7c2'
down_revision: Union[str, None] = '37603be3bd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'sales_rep', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('leads', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('lead_status', sa.String(), nullable=True))
    op.execute("UPDATE leads SET lead_status = 'unassigned' WHERE lead_status IS NULL")
    op.alter_column('leads', 'lead_status', existing_type=sa.String(), nullable=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_column('leads', 'lead_status')
    op.drop_column('leads', 'assigned_to')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
