"""auto schema sync

Revision ID: b1c30fd8ed5e
Revises: 26fe20795516
Create Date: 2026-02-19 15:52:46.435376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c30fd8ed5e'
down_revision: Union[str, None] = '26fe20795516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_migration_test_table_name', table_name='migration_test_table')
    op.drop_table('migration_test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migration_test_table_pkey')
    )
    op.create_index('ix_migration_test_table_name', 'migration_test_table', ['name'], unique=False)
    # ### end Alembic commands ###
